#:schema https://mise.jdx.dev/schema/mise.plugin.json

[exec-env]
cache-key = [
  """
  {% if project_root %}
    {{ project_root | canonicalize }}
  {% endif %}
  """,
  """
  {% if opts.pyproject %}
    {{ opts.pyproject }}
  {% endif %}
  """
]

[list-bin-paths]
cache-key = [
  """
  {% if project_root %}
    {{ project_root | canonicalize }}
  {% endif %}
  """,
  """
  {% if opts.pyproject %}
    {{ opts.pyproject }}
  {% endif %}
  """
]
