name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 5

jobs:
  plugin_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: jdxcode/rtx-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir -p ~/.local/share/rtx/plugins
      - run: ln -s $PWD ~/.local/share/rtx/plugins/poetry
      - run: rtx i poetry@latest
      - run: rtx x poetry@latest -- poetry --version

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install rtx
        run: brew install rtx

      - name: Install bats-core
        run: brew install bats-core

      - name: Test plugin
        run: |
          mkdir -p ~/.local/share/rtx/plugins
          ln -s $PWD ~/.local/share/rtx/plugins/poetry
          make test
        env:
          GITHUB_API_TOKEN: ${{ github.token }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install ShellCheck
        run: brew install shellcheck

      - name: Run ShellCheck
        run: make lint

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install shfmt
        run: brew update && brew install shfmt

      - name: Run shfmt
        run: make fmt-check
